# Generated by Django 5.2.6 on 2025-12-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='division',
        ),
        migrations.AddField(
            model_name='fighter',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='fighter',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
