# Generated by Django 5.2.6 on 2025-12-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_remove_fighter_division_fighter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
