# Generated by Django 5.2.6 on 2025-12-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_alter_fighter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='fighters.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fighter',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
