# Generated by Django 5.2.6 on 2025-12-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_fighter_division_alter_fighter_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='bio_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='details_cover',
            field=models.ImageField(blank=True, null=True, upload_to='fighters/details/'),
        ),
    ]
