# Generated by Django 5.2.6 on 2025-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0005_fighter_bio_long_fighter_details_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='reach',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
