# Generated by Django 5.2.6 on 2026-01-31 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0006_fighter_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='ufcstats_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='draw',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
