# Generated by Django 5.2.9 on 2026-03-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0008_alter_fighter_age_alter_fighter_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='reach',
            new_name='height_in',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weight',
        ),
        migrations.AddField(
            model_name='fighter',
            name='reach_in',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
