# Generated by Django 5.2.6 on 2026-03-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0009_rename_reach_fighter_height_in_remove_fighter_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='details_cover',
        ),
    ]
