# Generated by Django 5.2.6 on 2026-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0010_remove_fighter_details_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='details_cover',
            field=models.ImageField(blank=True, null=True, upload_to='fighters/details/'),
        ),
    ]
