# Generated by Django 5.2.6 on 2026-03-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0011_fighter_details_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='details_cover',
        ),
    ]
