# Generated by Django 5.2.6 on 2025-12-18 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UFCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UFCFight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bout', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('weightclass', models.CharField(blank=True, max_length=50)),
                ('method', models.CharField(blank=True, max_length=120)),
                ('round', models.PositiveSmallIntegerField(blank=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('time_format', models.CharField(blank=True, max_length=20)),
                ('referee', models.CharField(blank=True, max_length=60)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='ufcstats.ufcevent')),
            ],
        ),
        migrations.CreateModel(
            name='UFCFightStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter_name', models.CharField(max_length=255)),
                ('round', models.PositiveSmallIntegerField()),
                ('kd', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('sig_str', models.CharField(blank=True, max_length=30)),
                ('sig_str_pct', models.CharField(blank=True, max_length=10)),
                ('total_str', models.CharField(blank=True, max_length=30)),
                ('td', models.CharField(blank=True, max_length=30)),
                ('td_pct', models.CharField(blank=True, max_length=10)),
                ('sub_att', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('rev', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('ctrl', models.CharField(blank=True, max_length=20)),
                ('head', models.CharField(blank=True, max_length=30)),
                ('body', models.CharField(blank=True, max_length=30)),
                ('leg', models.CharField(blank=True, max_length=30)),
                ('distance', models.CharField(blank=True, max_length=30)),
                ('clinch', models.CharField(blank=True, max_length=30)),
                ('ground', models.CharField(blank=True, max_length=30)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='ufcstats.ufcfight')),
            ],
            options={
                'indexes': [models.Index(fields=['fighter_name'], name='ufcstats_uf_fighter_e93269_idx'), models.Index(fields=['round'], name='ufcstats_uf_round_6510fa_idx')],
            },
        ),
    ]
